name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        run: |
          touch .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env 
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env 
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env 
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env 
          echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env 

          echo COCONNECT_DB_ENGINE=django.db.backends.postgresql >> .env  
          echo COCONNECT_DB_HOST=\${POSTGRES_HOST} >> .env  
          echo COCONNECT_DB_PORT=\${POSTGRES_PORT} >> .env  
          echo COCONNECT_DB_NAME=\${POSTGRES_DB} >> .env  
          echo COCONNECT_DB_USER=\${POSTGRES_USER} >> .env  
          echo COCONNECT_DB_PASSWORD=\${POSTGRES_PASSWORD} >> .env  
          
          echo PROJECT_NAME=api >> .env 
          cat .env
      - name: Check .env file
        run: ls . && cat .env
      - name: Build the docker-compose stack
        run: docker-compose build 
      - name: Run the dokcer-compose stack
        run: |
          docker-compose up -d
          sleep 30
          if docker-compose logs | grep -i -q ERROR  ; then
              docker-compose logs | grep -i ERROR
              docker-compose logs api 
              echo "Errors found"
              exit 1
          else
             echo "No errors found!"
          fi 
          docker-compose down
